force-app/main/default/objects/NaturalLanguageForm__mdt/NaturalLanguageForm__mdt.object-meta.xml
<CustomObject>
    <label>Natural Language Form</label>
    <pluralLabel>Natural Language Forms</pluralLabel>
</CustomObject>

force-app/main/default/objects/NaturalLanguageFormComponent__mdt/NaturalLanguageFormComponent__mdt.object-meta.xml
<CustomObject>
    <label>Natural Language Form Component</label>
    <pluralLabel>Natural Language Form Components</pluralLabel>
</CustomObject>

force-app/main/default/objects/NaturalLanguageFormComponent__mdt/fields/Flow__c.field-meta.xml
<CustomField>
    <fullName>Flow__c</fullName>
    <label>Flow</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NaturalLanguageFormComponent__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NaturalLanguageFormComponent__mdt/fields/NaturalLanguageForm__c.field-meta.xml
<CustomField>
    <fullName>NaturalLanguageForm__c</fullName>
    <label>Natural Language Form</label>
    <referenceTo>NaturalLanguageForm__mdt</referenceTo>
    <relationshipLabel>Natural Language Form Components</relationshipLabel>
    <relationshipName>Natural_Language_Form_Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/NaturalLanguageFormComponent__mdt/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NaturalLanguageFormComponent__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Label</fullName>
                <default>true</default>
                <label>Label</label>
            </value>
            <value>
                <fullName>Input_text</fullName>
                <label>Input - text</label>
            </value>
            <value>
                <fullName>Input_date</fullName>
                <label>Input - date</label>
            </value>
            <value>
                <fullName>Input_number</fullName>
                <label>Input - number</label>
            </value>
            <value>
                <fullName>Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/selectors/NaturalLanguageFormComponentsSelector.cls
public inherited sharing class NaturalLanguageFormComponentsSelector {

    public List<NaturalLanguageFormComponent__mdt> selectComponentsByFormName(Set<String> formNames) {
        return [select DeveloperName, Sequence__c, Name__c, Type__c, Value__c, Flow__c
              from NaturalLanguageFormComponent__mdt 
              where NaturalLanguageForm__r.DeveloperName in :formNames
              order by Sequence__c];
    }

    public List<NaturalLanguageFormComponent__mdt> selectComponentsByDeveloperName(Set<String> developerNames) {
        return [select DeveloperName, Sequence__c, Name__c, Type__c, Value__c, Flow__c
              from NaturalLanguageFormComponent__mdt 
              where DeveloperName in :developerNames];
    }
}