force-app/main/default/objects/NaturalLanguageForm__mdt/NaturalLanguageForm__mdt.object-meta.xml
<CustomObject>
    <label>Natural Language Form</label>
    <pluralLabel>Natural Language Forms</pluralLabel>
</CustomObject>

force-app/main/default/objects/NaturalLanguageForm__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>Optionally set this to restrict this form for use only on the given objects record page.</inlineHelpText>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Natural Language Forms</relationshipLabel>
    <relationshipName>NaturalLanguageForms</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/selectors/NaturalLanguageFormSelector.cls
public inherited sharing class NaturalLanguageFormSelector {

    public NaturalLanguageForm__mdt getDefault(String filterByEntityName) {
        List<NaturalLanguageForm__mdt> forms = 
            [select DeveloperName, MasterLabel
                from NaturalLanguageForm__mdt 
                where Object__c = null or Object__c = :filterByEntityName
                order by MasterLabel ASC LIMIT 1];        
        return forms.size() > 0 ? forms[0] : null;
    }

    public List<NaturalLanguageForm__mdt> selectAll(String filterByEntityName) {
        return [select DeveloperName, MasterLabel
                from NaturalLanguageForm__mdt 
                where Object__c = null or Object__c = :filterByEntityName
                order by MasterLabel];
    }
}