force-app/main/default/objects/NaturalLanguageFormComponent__mdt/NaturalLanguageFormComponent__mdt.object-meta.xml
<CustomObject>
    <label>Natural Language Form Component</label>
    <pluralLabel>Natural Language Form Components</pluralLabel>
</CustomObject>

force-app/main/default/objects/NaturalLanguageFormComponent__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NaturalLanguageFormComponent__mdt/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NaturalLanguageFormComponent__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Label</fullName>
                <default>true</default>
                <label>Label</label>
            </value>
            <value>
                <fullName>Input_text</fullName>
                <label>Input - text</label>
            </value>
            <value>
                <fullName>Input_date</fullName>
                <label>Input - date</label>
            </value>
            <value>
                <fullName>Input_number</fullName>
                <label>Input - number</label>
            </value>
            <value>
                <fullName>Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/controllers/NaturalLanguageFormComponent.cls
public with sharing class NaturalLanguageFormComponent {

    @AuraEnabled
    public Integer sequence;
    @AuraEnabled
    public Boolean label;
    @AuraEnabled    
    public Boolean input;
    @AuraEnabled    
    public Boolean action;
    @AuraEnabled    
    public String type;
    @AuraEnabled    
    public String name;
    @AuraEnabled    
    public String value;

    public NaturalLanguageFormComponent(NaturalLanguageFormComponent__mdt formComponent) {
        sequence = Integer.valueOf(formComponent.Sequence__c);
        value = formComponent.Value__c;
        name = formComponent.Name__c == null ? formComponent.DeveloperName : formComponent.Name__c;
        switch on formComponent.Type__c {
            when 'Label' { label = true; }
            when 'Action' { action = true; }
            when else {
                if(formComponent.Type__c!=null && 
                   formComponent.Type__c.startsWith('Input')) {
                    input = true;
                    type = formComponent.Type__c.replace('Input_', '');
                }
            }
        }
    }
}